version: 2
jobs:
  build_docs:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout

      # Install documentation requirements
      - run:
          name: Install doc dependencies
          command: |
            sudo pip install -r doc/doc-requirements.txt

      # Build the docs
      - run:
          name: Build docs to store
          command: |
            cd doc
            make html

      - store_artifacts:
          path: doc/build/html/
          destination: html

workflows:
  version: 2
  default:
    jobs:
      - build_docs
