# Need to install bqplot with conda so it calls the javascript extension.
name: bqplot
channels:
  - conda-forge
  - anaconda
dependencies:
  - bqplot=0.9.0
  - pip:
    - sphinx
    - recommonmark
    - numpy
    - ipywidgets==6  # Because the default will be 5
    - traitlets
    - bs4
